# Generated by Django 6.0.6 on 2026-07-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_engine', '0002_movie_cast_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
