# Generated by Django 6.0.6 on 2026-07-24 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_engine', '0004_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='last_position',
            field=models.PositiveBigIntegerField(default=0, help_text='Playback position in seconds'),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='progress',
            field=models.PositiveBigIntegerField(default=0, help_text='Percentage watched (0-100)'),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='platform_engine.movie'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together={('user', 'movie')},
        ),
    ]
