# Generated by Django 6.0.6 on 2026-08-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_engine', '0010_movie_budget_movie_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
