# Generated by Django 6.0.6 on 2026-08-09 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_engine', '0011_movie_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='interactiontelemetry',
            options={},
        ),
        migrations.RemoveField(
            model_name='watchhistory',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='movie',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='interactiontelemetry',
            name='interaction_type',
            field=models.CharField(choices=[('CLICK', 'CLICK'), ('WATCH', 'WATCH'), ('TRAILER', 'TRAILER'), ('RATING', 'RATING'), ('VIEW', 'VIEW')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_companies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='last_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='movies', to='platform_engine.genre'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
