# Generated by Django 6.0.6 on 2026-08-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_engine', '0013_alter_collection_created_at'),
        ('platform_engine', '0014_auto_20260809_1801'),
    ]

    operations = [
    ]
