# Generated by Django 6.0.6 on 2026-08-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_engine', '0016_alter_movie_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('known_for_department', models.CharField(blank=True, max_length=255, null=True)),
                ('popularity', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movies', models.ManyToManyField(blank=True, related_name='actors', to='platform_engine.movie')),
            ],
        ),
    ]
