# Generated by Django 6.0.6 on 2026-08-11 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_engine', '0018_create_movie_genre_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('accuracy', models.CharField(default='96%', max_length=50)),
                ('algorithm', models.CharField(default='TF-IDF + Cosine Similarity', max_length=255)),
                ('trained_movies', models.IntegerField(default=0)),
                ('model_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='algorithm',
            field=models.CharField(default='TF-IDF', max_length=100),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='popularity_score',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['user', '-watched_at'], name='platform_en_user_id_f27cec_idx'),
        ),
    ]
