# Generated by Django 6.0.6 on 2026-08-11 06:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_engine', '0019_aimodelversion_alter_watchhistory_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('algorithm', models.CharField(max_length=255)),
                ('movies_processed', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('RUNNING', 'RUNNING')], default='RUNNING', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMoviePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_score', models.FloatField(default=0)),
                ('interaction_count', models.IntegerField(default=0)),
                ('liked', models.BooleanField(default=False)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTasteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality', models.CharField(default='Cinema Explorer', max_length=255)),
                ('favorite_genres', models.JSONField(default=list)),
                ('favorite_directors', models.JSONField(default=list)),
                ('favorite_actors', models.JSONField(default=list)),
                ('preferred_rating', models.FloatField(default=0)),
                ('taste_score', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_quote',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usergenrepreference',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usergenrepreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='popularity',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='movies',
            field=models.ManyToManyField(related_name='collections', to='platform_engine.movie'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='interactiontelemetry',
            name='interaction_type',
            field=models.CharField(choices=[('CLICK', 'CLICK'), ('WATCH', 'WATCH'), ('TRAILER', 'TRAILER'), ('RATING', 'RATING'), ('VIEW', 'VIEW'), ('WISHLIST', 'WISHLIST')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='algorithm',
            field=models.CharField(choices=[('TF-IDF', 'TF-IDF Content Based'), ('COLLABORATIVE', 'Collaborative Filtering'), ('HYBRID', 'Hybrid AI Model')], default='HYBRID', max_length=100),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='platform_engine.movie'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usergenrepreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('movie', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='usergenrepreference',
            unique_together={('user', 'genre')},
        ),
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together={('user', 'movie')},
        ),
        migrations.AddIndex(
            model_name='actor',
            index=models.Index(fields=['name', 'popularity'], name='platform_en_name_0389b0_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodelversion',
            index=models.Index(fields=['is_active'], name='platform_en_is_acti_fb1cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='interactiontelemetry',
            index=models.Index(fields=['user', 'interaction_type'], name='platform_en_user_id_a61e54_idx'),
        ),
        migrations.AddIndex(
            model_name='interactiontelemetry',
            index=models.Index(fields=['movie', 'timestamp'], name='platform_en_movie_i_909908_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['vote_average', 'popularity_score'], name='platform_en_vote_av_5f8c15_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_year'], name='platform_en_release_a5b1b9_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', '-score'], name='platform_en_user_id_2e7bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['movie', '-score'], name='platform_en_movie_i_c0e32e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['movie', '-created_at'], name='platform_en_movie_i_d1bffe_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', '-searched_at'], name='platform_en_user_id_a1a207_idx'),
        ),
        migrations.AddIndex(
            model_name='usergenrepreference',
            index=models.Index(fields=['user', '-score'], name='platform_en_user_id_ffc464_idx'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['movie', '-watched_at'], name='platform_en_movie_i_30708a_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'created_at'], name='platform_en_user_id_c9bea8_idx'),
        ),
        migrations.AddField(
            model_name='usermoviepreference',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='platform_engine.movie'),
        ),
        migrations.AddField(
            model_name='usermoviepreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertasteprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taste_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usermoviepreference',
            index=models.Index(fields=['user', '-preference_score'], name='platform_en_user_id_1b54f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermoviepreference',
            unique_together={('user', 'movie')},
        ),
    ]
