# Generated by Django 6.0.6 on 2026-08-11 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_engine', '0020_aitraininglog_usermoviepreference_usertasteprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(default='Hybrid AI', max_length=100)),
                ('score', models.FloatField(default=0)),
                ('clicked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='aimodelversion',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aimodelversion',
            name='framework',
            field=models.CharField(default='Scikit-Learn', max_length=100),
        ),
        migrations.AddField(
            model_name='aimodelversion',
            name='model_type',
            field=models.CharField(choices=[('CONTENT', 'Content Based'), ('SEMANTIC', 'Semantic AI'), ('HYBRID', 'Hybrid Recommendation'), ('COLLABORATIVE', 'Collaborative Filtering')], default='CONTENT', max_length=50),
        ),
        migrations.AddField(
            model_name='aimodelversion',
            name='training_time',
            field=models.FloatField(default=0, help_text='Training duration in seconds'),
        ),
        migrations.AddField(
            model_name='aimodelversion',
            name='vector_dimension',
            field=models.IntegerField(default=0, help_text='Embedding vector size'),
        ),
        migrations.AlterField(
            model_name='aimodelversion',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddIndex(
            model_name='aimodelversion',
            index=models.Index(fields=['model_type'], name='platform_en_model_t_2eadf3_idx'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_engine.movie'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['user', 'created_at'], name='platform_en_user_id_f6f807_idx'),
        ),
    ]
