# Generated by Django 6.0.6 on 2026-08-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_engine', '0022_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertasteprofile',
            name='preferred_experience',
            field=models.CharField(default='Immersive World Building', max_length=150),
        ),
        migrations.AddField(
            model_name='usertasteprofile',
            name='watching_style',
            field=models.FloatField(default=0),
        ),
    ]
