# Generated by Django 6.0.6 on 2026-08-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_engine', '0023_usertasteprofile_preferred_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertasteprofile',
            name='watching_style',
            field=models.CharField(default='Balanced Cinema Explorer', max_length=150),
        ),
    ]
