# Generated by Django 6.0.6 on 2026-08-14 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_engine', '0024_alter_usertasteprofile_watching_style'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUserInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality', models.CharField(default='Cinema Explorer', max_length=100)),
                ('ai_summary', models.TextField(blank=True)),
                ('taste_score', models.IntegerField(default=50)),
                ('story_score', models.IntegerField(default=50)),
                ('visual_score', models.IntegerField(default=50)),
                ('emotion_score', models.IntegerField(default=50)),
                ('action_score', models.IntegerField(default=50)),
                ('complexity_score', models.IntegerField(default=50)),
                ('movie_analyzed', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
